//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffOfHospital
    {
        public string StaffHId { get; set; }
        public string StaffHName { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string HospitalID { get; set; }
    
        public virtual Hospital Hospital { get; set; }
    }
}
